from collections.abc import Buffer
from typing import Protocol


class UnsizedProtocolLayer(Protocol):
    def recv(self, bufsize: int, /) -> bytes: ...
    def sendall(self, data: Buffer, /) -> None: ...


class SizedProtocolLayer(Protocol):
    def recv(self, /) -> bytes: ...
    def send(self, data: Buffer, /) -> None: ...
